CREATE TABLE "world_data" (
    ID INT NOT NULL PRIMARY KEY,
    "Country" varchar(255),
    "Region" varchar(255),
    "Happiness Rank" INT,
    "Happiness Score" DECIMAL,
    "Standard Error" DECIMAL,
	"Economy (GDP per Capita)" DECIMAL,
	"Family"  DECIMAL,
    "Health (Life Expectancy)"  DECIMAL,
	"Freedom"  DECIMAL,
	"Trust (Government Corruption)"  DECIMAL,
	"Generosity"  DECIMAL,
	"Dystopia Residual"  DECIMAL,
    "Bird Species, Threatened" FLOAT,
    "Fish species, threatened" FLOAT,
    "Plant species (higher), threatened" FLOAT,
    "Mammal species, threatened" FLOAT,
    "Distance to frontier score" FLOAT,
    "Business extent of disclosure index" FLOAT,
    "Ease of doing business index" FLOAT,
    "Depth of credit information index" FLOAT,
    "Private credit bureau coverage (% of adults)" FLOAT,
    "Public credit registry coverage (% of adults)" FLOAT,
    "Time required to get electricity (days)" FLOAT,
    "Time to resolve insolvency (years)" FLOAT,
    "Strength of legal rights index" FLOAT,
    "Time required to enforce a contract (days)" FLOAT,
    "Time required to register property (days)" FLOAT,
    "Procedures to register property (number)" FLOAT,
    "Cost of business start-up procedures (%)" FLOAT,
    "Time required to start a business (days)" FLOAT,
    "Start-up procedures to register a business (number)" FLOAT,  
    "Time to prepare and pay taxes (hours)" FLOAT,
    "Tax payments (number)" FLOAT,
    "Total tax rate (% of commercial profits)" FLOAT,
    "Time required to build a warehouse (days)" FLOAT,
    "Procedures to build a warehouse (number)" FLOAT,
    "Proportion of seats held by women in parliaments (%)" DECIMAL,
    "Number of infant deaths" FLOAT,    
    "Number of under-five deaths" FLOAT,
    "Number of neonatal deaths" FLOAT,
    "Mortality rate, under-5(per 1,000)" FLOAT,
    "Mortality rate, under-5, female(per 1,000)" FLOAT,
    "Mortality rate, under-5, male(per 1,000)" FLOAT,
    "Mortality rate, neonatal(per 1,000)" FLOAT,
    "Improved water source, rural (%)" FLOAT,
    "Improved water source, urban (%)" FLOAT,
    "Improved water source (%)" FLOAT,
    "Number of maternal deaths" FLOAT,
    "Lifetime risk of maternal death" FLOAT,
    "Lifetime risk of maternal death (%)" DECIMAL,
    "Improved sanitation facilities (%)" FLOAT,
    "Improved sanitation facilities, rural (%)" FLOAT,
    "Improved sanitation facilities, urban (%)" FLOAT,
    "Maternal mortality ratio(per 100,000)" FLOAT,
    "Mortality rate, infant, female(per 1,000)" FLOAT,
    "Mortality rate, infant(per 1,000)" FLOAT,
    "Mortality rate, infant, male(per 1,000)" FLOAT);